services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GOOS=${GOOS}"
      - "GOARCH={GOARCH}"
    image: poptape/reviews/api:v0.1
    ports:
      - "1244:8020"
    restart: always
    depends_on:
      - db
    networks:
      - poptape
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "1245:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - poptape_reviews_data:/var/lib/postgresql/data
    networks:
      - poptape
networks:
  poptape:
    external: true
volumes:
  poptape_reviews_data: