services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "GOOS=${GOOS}"
      - "GOARCH=${GOARCH}"
      - "PORT=${PORT}"
    image: poptape/reviews/api:v${VERSION}
    ports:
      - "1244:${PORT}"
    restart: always
    volumes:
      - ${LOCAL_LOG_LOC}:/reviews/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    depends_on:
      - db
    networks:
      - poptape
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "1245:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - poptape_reviews_data:/var/lib/postgresql/data
    networks:
      - poptape
networks:
  poptape:
    external: true
volumes:
  poptape_reviews_data:
    name: poptape_reviews_data