name: Build and test
on: push

#env:
#  GOPROXY: github.com/cliveyg/poptape-reviews
#

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    services:
      # label used to access the service container
      postgres:
        # dockerhub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: testpass
          POSTGRES_USER: poptape_reviews_test
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # maps tcp port 5432 on service container to the host
          - 5432:5432    
    container:
      image: ubuntu:latest
      volumes:
        - ${{ github.workspace }}:/app
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: install go dependencies
        env:
          GOPROXY: proxy.golang.org,direct
        run: |
          rm -f go.mod go.sum
          go mod init github.com/cliveyg/poptape-reviews
          go mod tidy
